// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx-uPHrdk8g0pMXRnFMLVZK-Ekp7vF_0c',
    appId: '1:202903213493:web:6607d30374a54b816475fc',
    messagingSenderId: '202903213493',
    projectId: 'student-port-c32fe',
    authDomain: 'student-port-c32fe.firebaseapp.com',
    storageBucket: 'student-port-c32fe.appspot.com',
    measurementId: 'G-H83XVR9EZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGrqvfYxe3V-U6PFw06xvgpwA0kx-_OMk',
    appId: '1:202903213493:android:57c78aa1b7b6cbff6475fc',
    messagingSenderId: '202903213493',
    projectId: 'student-port-c32fe',
    storageBucket: 'student-port-c32fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYXXDG5iq3txjUSj2Paec4fx4mYgDZds',
    appId: '1:202903213493:ios:b5189cc08391dbf46475fc',
    messagingSenderId: '202903213493',
    projectId: 'student-port-c32fe',
    storageBucket: 'student-port-c32fe.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYXXDG5iq3txjUSj2Paec4fx4mYgDZds',
    appId: '1:202903213493:ios:8e623051fc472d646475fc',
    messagingSenderId: '202903213493',
    projectId: 'student-port-c32fe',
    storageBucket: 'student-port-c32fe.appspot.com',
    iosBundleId: 'com.example.student.RunnerTests',
  );
}
